#!/bin/zsh

cp -R /Users/calvinwchang2/Library/Mobile\ Documents/com\~apple\~CloudDocs/Programming/2025/Javascript\:HTML/fluid\ simulation/Cup-Sim/v2/Application /Users/calvinwchang2/Library/Mobile\ Documents/com\~apple\~CloudDocs/Programming/2025/Javascript\:HTML/fluid\ simulation/Cup-Sim/v2/backups/"$(date)"
exit
